### ISSUE TITLE
CODEOWNERS <-> OWNERS

### ISSUE THREAD

**Issue by ctiller** [bkeepers/OWNERS#7]
As an FYI, over on https://github.com/grpc/grpc we're adopting this format for OWNERS files, and have built a conversion script between this format and the new .github/CODEOWNERS format supported by GitHub.

An initial script to do the conversion is included in https://github.com/grpc/grpc/pull/11774.

If there's interest, I'd be happy to get a PR together to share this work here.

**Comment by gjtorikian** [comment]
Please see https://github.com/bkeepers/OWNERS/pull/6#issuecomment-314157339. This is not the repository that powers the feature.

@bkeepers I'm going to unwatch the repo; seems like our little project has taken off an gone into a different direction. 😆  It was a good spike.

**Comment by ctiller** [comment]
I realize this isn't the code that powers the feature. What we've done is to add a conversion script between this and the CODEOWNERS feature (since we've got some reservations about CODEOWNERS being scalable enough for our purposes).
